% 1. Process nVoke recorded files in recording folder: PP, BP, MC and DFF. Copy these files and GPIO
% info to project forlder
nvoke_file_process;

% 2. Draw ROIs with Inscopix Data Processing Software (IDPS)
% 	- Export ROI info as .csv
% 	- Export GPIO info as .csv if exists
% 	- Check each recording with plot app: 'D:\guoda\Documents\MATLAB\Codes\nvoke-analysis\plot_roi_gpio_App.mlapp'
		plot_roi_gpio_App.mlapp

% 3. Convert ROI info to matlab file (.m). Copy ROI info (csv files) to analysis folder, and run this
% function
[ROIdata, recording_num, cell_num] = ROIinfo2matlab;

% 4. Check data with plot function
[ROIdata_peakevent] = nvoke_event_detection(ROIdata,1, 1); % plot with pause. (ROIdata, 2, 1) plot and save with pause
[ROIdata_peakevent] = nvoke_event_detection(ROIdata,2, 0); % plot and save without pause

% 5. Delete bad/usless cells in ROIdata generated by previous steps. Check data with plot function again
[modified_ROIdata] = nvoke_correct_peakdata(ROIdata_peakevent,1,1); 

% 6. Check peaks and their start and end point. Manully correct these numbers and go through step 5 function.
[modified_ROIdata] = nvoke_correct_peakdata(modified_ROIdata,2,1); % save plots with pauses 

% 7. Calculate peak amplitude, rise and decay duration. Plot correlations
[peak_info_sheet, total_cell_num, total_peak_num] = nvoke_event_calc(modified_ROIdata, 1);