function [stimEvent_possibility_all,varargout] = collect_stimEvent_possibility(alignedData,varargin)
% Collect the possibility of the stimulation related events from all ROIs and all trials stored in alignedData
% possibility info is stored in alignedData_allTrials(n).traces(m).stimEvent_possi  

% alignedData: structure var containing info from all trials
%		- Generated by function [get_event_trace_allTrials] from recdata_organized var

	% Defaults
    modify_stim_name = true; % true/false. Change the stimulation name, 
                                % such as GPIOxxx and OG-LEDxxx (output from nVoke), to simpler ones (ap, og, etc.)
	debug_mode = false; % true/false


	% Optionals
	for ii = 1:2:(nargin-2)
	    if strcmpi('modify_stim_name', varargin{ii})
	        modify_stim_name = varargin{ii+1}; % 
	    % elseif strcmpi('cat_exclude', varargin{ii})
	    %     cat_exclude = varargin{ii+1}; 
	    elseif strcmpi('debug_mode', varargin{ii})
	        debug_mode = varargin{ii+1}; 
	    end
	end

	% ====================
	% Main contents
	trial_num = numel(alignedData);

	for tn = 1:trial_num
		alignedData_trial = alignedData(tn);
		trialName = alignedData_trial.trialName;
		stimName = alignedData_trial.stim_name;
	    fovID = alignedData_trial.fovID;

	    if debug_mode
	        fprintf('trial %d: %s\n', tn, trialName)
	        if tn == 36
	            pause
	        end
	    end

		roi_num = numel(alignedData_trial.traces);
    	for rn = 1:roi_num
    		roiData = alignedData_trial.traces(rn);
    		roiName = roiData.roi; 

    		if ~isempty(roiData.stimEvent_possi)
    			stimEvent_possibility = alignedData_trial.traces(rn).stimEvent_possi;

    			cat_name_old = {stimEvent_possibility.cat_name};
    			cat_name_new = cellfun(@(x) sprintf('%s[%s]',x,stimName),cat_name_old,'UniformOutput',false);
    			[stimEvent_possibility.cat_name] = cat_name_new{:};


    			[stimEvent_possibility.trialName] = deal(trialName); % add trial name to every entry
    			[stimEvent_possibility.fovID] = deal(fovID); % add trial name to every entry
    			[stimEvent_possibility.roiName] = deal(roiName); % add trial name to every entry

    			if ~exist('stimEvent_possibility_all','var')
    				stimEvent_possibility_all = stimEvent_possibility;
    			else
    				stimEvent_possibility_all = [stimEvent_possibility_all,stimEvent_possibility];
    			end
    		end
    	end
	end

	if modify_stim_name
		[cat_setting] = set_CatNames_for_mod_cat_name('stimulation'); % Get the settings to modify the stimulation names in ca_events 
		cat_num = numel(cat_setting.cat_names);
		for cn = 1:cat_num
			old_str = cellfun(@(x) sprintf('[%s]',x),cat_setting.cat_merge{cn},'UniformOutput',false);
			new_str = sprintf('[%s]', cat_setting.cat_names{cn});
			stimEvent_possibility_all = mod_struct_str(stimEvent_possibility_all,'cat_name',...
				old_str,new_str);
		end
	end
end
