function [empty_event_info_struct, varargout] = creat_event_struct
	% creat an empty event_info structure


	struct_field = {'recording_name', 'roi_name', 'idx_in_peak_table', 'events_time',...
	    'rise_time', 'rise_loc', 'peak_time', 'peak_loc',...
	    'peak_mag', 'peak_mag_norm', 'event_time_2_stim', 'event_time_2_stim_pre',...
	    'event_time_2_stim_post', 'spont_event_freq', 'stim_num_per_roi'};


	% empty_event_info_struct = struct(struct_field{1}, {}, struct_field{2}, {}, struct_field{3}, {}, struct_field{4}, {},...
	%     struct_field{5}, {}, struct_field{6}, {}, struct_field{7}, {}, struct_field{8}, {},...
	%     struct_field{9}, {}, struct_field{10}, {}, struct_field{11}, {}, struct_field{12}, {},...
	%     struct_field{13}, {}, struct_field{14}, {}, struct_field{15}, {});

	empty_event_info_struct = struct(struct_field{1}, {NaN}, struct_field{2}, {NaN}, struct_field{3}, {NaN}, struct_field{4}, {NaN},...
	    struct_field{5}, {NaN}, struct_field{6}, {NaN}, struct_field{7}, {NaN}, struct_field{8}, {NaN},...
	    struct_field{9}, {NaN}, struct_field{10}, {NaN}, struct_field{11}, {NaN}, struct_field{12}, {NaN},...
	    struct_field{13}, {NaN}, struct_field{14}, {NaN}, struct_field{15}, {NaN});


	varargout{1} = struct_field;
end