function fNum = nNumberTab(structDataForPlot,entryType)
    % Create an UI table showing the n numbers (event, trial, animal, roi, etc.) 

    % structDataForPlot: A structure var generated by the function 'getAndGroup_eventsProp'. It is
    % used to create various plots by the function 'plot_event_info'

    % entryType: 'roi' or 'event'. It is also the input for the function 'getAndGroup_eventsProp'
    % used to create 'structDataForPlot'

    % Defaults
    fNum = figure('Name', 'n numbers');
    fig_position = [0.1 0.1 0.3 0.2]; % left, bottom, width, height
    ax = axes(fNum, 'Position', [0.1, 0.1, 0.8, 0.8], 'Units', 'normalized', 'Visible', 'on'); % Axes turned off after positioning

    nNumStr = sprintf('n number = the number of %s', entryType);
    title(nNumStr);

    set(fNum, 'Units', 'normalized', 'Position', fig_position)
    uit_pos = get(ax,'Position');
    % uit_unit = get(ax,'Units');

    % Add event number to the 'structDataForPlot' if entryType is 'event'
    switch entryType
        case 'event'
            % Convert the event_info field into a cell array and count the number of events 
            eventInfoCellArray = {structDataForPlot.event_info};
            eventNumCell = cellfun(@numel,eventInfoCellArray,'UniformOutput',false);

            % Add event number to the 'structDataForPlot'
            structDataForPlot = addNewField2Struct(structDataForPlot,'eventNum',eventNumCell);

            % Convert the 'structDataForPlot' to a table var
            T = struct2table(structDataForPlot,"AsArray",true);

            % Select the columns for showing in the UI table
            T = T(:,["group","animalNum","recNum","roiNum","eventNum"]);

        case 'roi'
            % Convert the 'structDataForPlot' to a table var
            T = struct2table(structDataForPlot,"AsArray",true);

            % Select the columns for showing in the UI table
            T = T(:,["group","animalNum","recNum","roiNum"]);
        otherwise
            error('entryType must be either "event" or "roi"')
    end

    % Generate column names and the string explaining the n number
    columnNames = T.Properties.VariableNames;


    % Create a UI table and fill it with T
    uit = uitable(fNum,'Data',table2cell(T),...
        'ColumnName', columnNames,...
        'Units','normalized','Position',uit_pos);
    % uit.ColumnWidth = 'auto';
    uit.ColumnWidth = {100, 150, 200};
    uit.FontSize = 12;
end
