function [varargout] = plot_event_info(event_info_struct,varargin)
	% Plot various event properties 
	% Input: 
	%	- structure array including one or more event_info structures {event_info1, event_info2,...}
	% Output:
	%	- event frequency histogram
	%	- event interval variance histogram
	%	- event rise_time bar
	%	- event peak amplitude bar
	%	- event rise_time/peak scatter and correlation
	%	- event peak-slope scatter and correlation
	%	- event slope bar

	% Defaults
	plot_combined_data = false; % applied to histogram plots
	save_fig = false;
	save_dir = '';

	% Optionals
	for ii = 1:2:(nargin-1)
	    if strcmpi('plot_combined_data', varargin{ii})
	        plot_combined_data = varargin{ii+1};
        elseif strcmpi('save_fig', varargin{ii})
            save_fig = varargin{ii+1};
        elseif strcmpi('save_dir', varargin{ii})
            save_dir = varargin{ii+1};
	    end
	end

	if save_fig 
		save_dir = uigetdir(save_dir,...
			'Choose a folder to save plots');
	end


	close all

	group_num = numel(event_info_struct);

	% Histogram plot
	[hist_info_freq, hist_info_freq_setting] = plot_event_info_hist(event_info_struct,...
		'freq', 'plot_combined_data', plot_combined_data,...
		'save_fig', save_fig, 'save_dir', save_dir);

	[hist_info_interval, hist_info_interval_setting] = plot_event_info_hist(event_info_struct,...
		'events_interval_time_mean', 'plot_combined_data', plot_combined_data,...
		'save_fig', save_fig, 'save_dir', save_dir);

	[hist_info_rise_duration, hist_info_rise_duration_setting] = plot_event_info_hist(event_info_struct,...
		'rise_duration_mean', 'plot_combined_data', plot_combined_data,...
		'save_fig', save_fig, 'save_dir', save_dir);

	[hist_info_peak_mag, hist_info_peak_mag_setting] = plot_event_info_hist(event_info_struct,...
		'peak_mag_mean', 'plot_combined_data', plot_combined_data,...
		'save_fig', save_fig, 'save_dir', save_dir);
	[hist_info_peak_mag_norm, hist_info_peak_mag_norm_setting] = plot_event_info_hist(event_info_struct,...
		'peak_mag_norm_mean', 'plot_combined_data', plot_combined_data,...
		'save_fig', save_fig, 'save_dir', save_dir);

	[hist_info_slope, hist_info_slope_setting] = plot_event_info_hist(event_info_struct,...
		'peak_slope_mean', 'plot_combined_data', plot_combined_data,...
		'save_fig', save_fig, 'save_dir', save_dir);
	[hist_info_slope_norm, hist_info_slope_norm_setting] = plot_event_info_hist(event_info_struct,...
		'peak_slope_norm_hpstd_mean', 'plot_combined_data', plot_combined_data,...
		'save_fig', save_fig, 'save_dir', save_dir);
	

	% Bar plot (Only when data is grouped to multiple categories)
	if group_num > 1
		[bar_data_rise_duration] = plot_event_info_bar(event_info_struct,...
			'rise_duration_mean',...
			'save_fig', save_fig, 'save_dir', save_dir);

		[bar_data_peak_mag] = plot_event_info_bar(event_info_struct,...
			'peak_mag_mean',...
			'save_fig', save_fig, 'save_dir', save_dir);
		[bar_data_peak_mag_norm] = plot_event_info_bar(event_info_struct,...
			'peak_mag_norm_mean',...
			'save_fig', save_fig, 'save_dir', save_dir);

		[bar_data_slope] = plot_event_info_bar(event_info_struct,...
			'peak_slope_mean',...
			'save_fig', save_fig, 'save_dir', save_dir);
		[bar_data_slope_norm] = plot_event_info_bar(event_info_struct,...
			'peak_slope_norm_hpstd_mean',...
			'save_fig', save_fig, 'save_dir', save_dir);
	end


	% Scatter plot
	[scatter_data_rise_VS_peak] = plot_event_info_scatter(event_info_struct,...
		'rise_duration_mean', 'peak_mag_mean',...
		'save_fig', save_fig, 'save_dir', save_dir);
	[scatter_data_rise_VS_peaknorm] = plot_event_info_scatter(event_info_struct,...
		'rise_duration_mean', 'peak_mag_norm_mean',...
		'save_fig', save_fig, 'save_dir', save_dir);

	[scatter_data_rise_VS_peak] = plot_event_info_scatter(event_info_struct,...
		'rise_duration_mean', 'peak_slope_mean',...
		'save_fig', save_fig, 'save_dir', save_dir);
	[scatter_data_rise_VS_peaknorm] = plot_event_info_scatter(event_info_struct,...
		'rise_duration_mean', 'peak_slope_norm_hpstd_mean',...
		'save_fig', save_fig, 'save_dir', save_dir);

	[scatter_data_rise_VS_peak] = plot_event_info_scatter(event_info_struct,...
		'peak_mag_mean', 'peak_slope_mean',...
		'save_fig', save_fig, 'save_dir', save_dir);
	[scatter_data_rise_VS_peaknorm] = plot_event_info_scatter(event_info_struct,...
		'peak_mag_norm_mean', 'peak_slope_norm_hpstd_mean',...
		'save_fig', save_fig, 'save_dir', save_dir);
	
end